//.$file${.::QPmodel::QPbsp.hpp} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: timebombQPmodel.qm
// File:  ${.::QPmodel::QPbsp.hpp}
//
// This code has been generated by QM 5.1.1 <www.state-machine.com/qm/>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// This program is open source software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
// for more details.
//
//.$endhead${.::QPmodel::QPbsp.hpp} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef QPBSP_HPP
#define QPBSP_HPP

// a very simple Board Support Package (BSP) -------------------------------
class QPBSP {
public:
    enum { TICKS_PER_SEC = 100 }; // number of clock ticks in a second
    static void init(void);
    static void ledOff(void);
    static void ledOn(void);
    static void readButton(void);
};

enum BlinkySignals {
    TIMEOUT_SIG = QP::Q_USER_SIG, // offset the first signal
    BUTTON_PRESSED_SIG,
    BUTTON_RELEASED_SIG,
    MAX_SIG
};

// active object(s) used in this application -------------------------------
//.$declare${AOs::AO_Timebomb} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
extern QP::QActive * const AO_Timebomb;
//.$enddecl${AOs::AO_Timebomb} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif // QPBSP_HPP